[theme]
# Primary colors
primaryColor = "#FF6B6B"          # Accent color (buttons, links)
backgroundColor = "#FFFFFF"       # Main background
secondaryBackgroundColor = "#F0F2F6"  # Sidebar, expanders
textColor = "#262730"             # Text color

# Font
font = "sans serif"  # "sans serif", "serif", or "monospace"